
raise ValueError('Invailid argument')


##  try:
##  .....
##  except Exception1:
##  .....
##  except Exception1:
##  .....
##  except:
##  .....
##  else:
##  .....
##  finally:


##  try:
##      pass
##  except Exception1:
##      pass
##  except (Exception2, Exception3):
##      pass
##  except Exception4 as exception:
##      pass
##  except Exception4, exception:
##      pass
##  except:
##      pass